//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP
{
    using System;
    using System.Collections.Generic;
    
    public partial class admins
    {
        public int id_admin { get; set; }
        public string admin_login { get; set; }
        public string admin_password { get; set; }
        public string admin_name { get; set; }
        public string admin_lastname { get; set; }
        public string admin_secondname { get; set; }
        public Nullable<System.DateTime> dateofbirth { get; set; }
        public string email { get; set; }
    }
}
