//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP
{
    using System;
    using System.Collections.Generic;
    
    public partial class films
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public films()
        {
            this.marks = new HashSet<marks>();
            this.role_actors = new HashSet<role_actors>();
        }
    
        public int id_film { get; set; }
        public Nullable<int> id_country { get; set; }
        public string name_film { get; set; }
        public Nullable<System.DateTime> date_creation { get; set; }
        public Nullable<int> rating { get; set; }
        public Nullable<int> id_genre { get; set; }
        public byte[] film_photo { get; set; }
        public string film_link { get; set; }
    
        public virtual countries countries { get; set; }
        public virtual genres genres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<marks> marks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<role_actors> role_actors { get; set; }
    }
}
